#!/bin/bash
# Initialize infrastructure from scratch
# Creates AKS cluster, DNS, storage, and communication services

set -e

cd "$(dirname "$0")/../infrastructure"

echo "=== Initializing Terraform ==="
terraform init

echo ""
echo "=== Creating base infrastructure ==="
echo "This will create:"
echo "  - AKS cluster (1 node)"
echo "  - Azure DNS zone"
echo "  - Storage account for videos"
echo "  - Communication services for email"
echo ""

# Stage 1: Create cluster, DNS, storage, email services (generates kubeconfig.yaml)
terraform apply \
  -var="kubernetes_resources_enabled=false" \
  -var="argocd_resources_enabled=false" \
  -var="email_domain_verified=false"

echo ""
echo "=== Installing Kubernetes resources (nginx, cert-manager, ArgoCD) ==="
# Stage 2: Install K8s resources and ArgoCD helm chart
# Note: kubeconfig.yaml already generated by Stage 1
terraform apply \
  -var="kubernetes_resources_enabled=true" \
  -var="argocd_resources_enabled=false" \
  -var="email_domain_verified=false"

echo ""
echo "✅ Infrastructure initialized!"
echo ""
echo "Next steps:"
echo "  1. Configure nameservers in your domain registrar:"
terraform output azure_nameservers
echo ""
echo "  2. Wait for DNS propagation (usually 5-60 minutes)"
echo ""
echo "  3. Verify email domain in Azure:"
echo "     - Go to Azure Portal -> Communication Services -> Email Services"
echo "     - Check domain verification status"
echo "     - Once verified, run: terraform apply -var='email_domain_verified=true'"
echo ""
echo "  4. Run ./enable-argo.sh to enable ArgoCD and continuous deployment"
