terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.20"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.7"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "~> 1.14"
    }
    rancher2 = {
      source  = "rancher/rancher2"
      version = "~> 8.3.1"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Environment = var.environment
      Project     = var.project_name
      ManagedBy   = "Terraform"
    }
  }
}

provider "aws" {
  alias  = "virginia"
  region = "us-east-1"

  default_tags {
    tags = {
      Environment = var.environment
      Project     = var.project_name
      ManagedBy   = "Terraform"
    }
  }
}

data "aws_partition" "current" {}

provider "kubernetes" {
  host  = var.kubernetes_resources_enabled && var.rancher_cluster_enabled ? yamldecode(rancher2_cluster_v2.main[0].kube_config).clusters[0].cluster.server : null
  token = var.kubernetes_resources_enabled && var.rancher_cluster_enabled ? yamldecode(rancher2_cluster_v2.main[0].kube_config).users[0].user.token : null
}

provider "helm" {
  kubernetes {
    host  = var.kubernetes_resources_enabled && var.rancher_cluster_enabled ? yamldecode(rancher2_cluster_v2.main[0].kube_config).clusters[0].cluster.server : null
    token = var.kubernetes_resources_enabled && var.rancher_cluster_enabled ? yamldecode(rancher2_cluster_v2.main[0].kube_config).users[0].user.token : null
  }
}

provider "kubectl" {
  host             = var.kubernetes_resources_enabled && var.rancher_cluster_enabled ? yamldecode(rancher2_cluster_v2.main[0].kube_config).clusters[0].cluster.server : null
  token            = var.kubernetes_resources_enabled && var.rancher_cluster_enabled ? yamldecode(rancher2_cluster_v2.main[0].kube_config).users[0].user.token : null
  load_config_file = false
}

output "kubeconfig_path" {
  description = "Path to kubeconfig file (auto-generated by Rancher after cluster creation)"
  value       = "${path.module}/kubeconfig.yaml"
}
