terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.20"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.7"
    }
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "~> 1.14"
    }
    rancher2 = {
      source  = "rancher/rancher2"
      version = "~> 8.3.1"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      Environment = var.environment
      Project     = var.project_name
      ManagedBy   = "Terraform"
    }
  }
}

provider "aws" {
  alias  = "virginia"
  region = "us-east-1"

  default_tags {
    tags = {
      Environment = var.environment
      Project     = var.project_name
      ManagedBy   = "Terraform"
    }
  }
}

data "aws_partition" "current" {}

provider "rancher2" {
  alias     = "bootstrap"
  api_url   = "https://rancher.${var.domain_name}"
  bootstrap = true
  insecure  = true
}

provider "rancher2" {
  api_url   = "https://rancher.${var.domain_name}"
  bootstrap = false
  insecure  = true
  token_key = var.rancher_cluster_enabled ? try(module.rancher_cluster[0].admin_token, "") : ""
}

provider "kubernetes" {
  host  = var.rancher_cluster_enabled ? try(module.rancher_cluster[0].kube_host, null) : null
  token = var.rancher_cluster_enabled ? try(module.rancher_cluster[0].kube_token, null) : null
}

provider "helm" {
  kubernetes {
    host  = var.rancher_cluster_enabled ? try(module.rancher_cluster[0].kube_host, null) : null
    token = var.rancher_cluster_enabled ? try(module.rancher_cluster[0].kube_token, null) : null
  }
}

provider "kubectl" {
  host             = var.rancher_cluster_enabled ? try(module.rancher_cluster[0].kube_host, null) : null
  token            = var.rancher_cluster_enabled ? try(module.rancher_cluster[0].kube_token, null) : null
  load_config_file = false
}

output "kubeconfig_path" {
  description = "Path to kubeconfig file (auto-generated by Rancher after cluster creation)"
  value       = "${path.module}/kubeconfig.yaml"
}
