terraform state rm  helm_release.argocd[0]
terraform state rm  helm_release.cert_manager[0]
terraform state rm  kubectl_manifest.gateway_api_crds[1]
terraform state rm  kubectl_manifest.gateway_api_crds[0]
terraform state rm  kubectl_manifest.gateway_api_crds[3]
terraform state rm  kubectl_manifest.gateway_api_crds[4]
terraform state rm  kubectl_manifest.gateway_api_crds[5]
terraform state rm  kubectl_manifest.gateway_api_crds[2]
terraform state rm rancher2_cluster_v2.main[0]
terraform state rm rancher2_machine_config_v2.nodes[0]
terraform state rm rancher2_cloud_credential.aws[0]
terraform state rm rancher2_bootstrap.admin[0] 
terraform state rm rancher2_setting.agenttlsmode[0]
terraform state rm  helm_release.external_dns[0]
terraform state rm  helm_release.kube_prometheus_stack[0]
terraform state rm  helm_release.nginx_gateway_fabric[0]
terraform state rm  kubectl_manifest.argocd_httproute[0]
terraform state rm  kubectl_manifest.letsencrypt_prod[0]kubectl_manifest.nginx_gateway[0]
terraform state rm  helm_release.loki[0]kubectl_manifest.grafana_httproute[0]
terraform state rm  kubectl_manifest.prometheus_httproute[0]
terraform state rm  kubectl_manifest.rabbitmq_httproute[0]
terraform state rm kubectl_manifest.letsencrypt_prod[0]
terraform state rm kubectl_manifest.nginx_gateway[0]
terraform state rm  helm_release.loki[0]
terraform state rm kubectl_manifest.grafana_httproute[0]
terraform state rm kubectl_manifest.argocd_certificate[0]
terraform state rm helm_release.promtail[0]
terraform state rm kubectl_manifest.grafana_certificate[0]
terraform state rm kubectl_manifest.prometheus_certificate[0]
terraform state rm kubectl_manifest.loki_httproute[0]
terraform state rm kubectl_manifest.loki_certificate[0]
terraform state rm kubectl_manifest.rabbitmq_certificate[0]


terraform apply
